apiVersion: v2
name: pagopa-biz-events-datastore
description: Microservice to store biz events to CosmosDB
type: application
version: 0.129.0
appVersion: 0.12.1-1-webhost-id-test
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-biz-events-datastore
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-biz-events-view
# - name: microservice-chart
#   version: 2.8.0
#   repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
#   alias: pagopa-biz-events-ingestion
